---
galaxy_info:
  author: Andrew
  description: Role for creating files using custom module
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  platforms:
    - name: Linux
  galaxy_tags:
    - file
    - custom
dependencies: []
